#!/usr/bin/env python3
"""AQ-PAGE-WOOTTERS-IBM-5 -- global stationarity, and its link to internal evolution.

IBM-0..IBM-4 measured one half of the Page-Wootters mechanism: conditioning on
a clock reading yields apparent dynamics, and the history state is genuinely
entangled (IBM-4). The OTHER half -- the half the mechanism is named for --
was never measured: that the global state is STATIONARY. "Evolution without
evolution" requires showing the "without evolution" part.

THE CONSTRAINT. Let S be the cyclic clock shift S|t> = |t+1 mod d> and U the
system's one-tick evolution. A Page-Wootters history state satisfies

    (S (x) U) |Psi> = |Psi>

i.e. it is invariant under advancing the clock AND evolving the system
together. This is the discrete, finite-dimensional analogue of the
Wheeler-DeWitt constraint J|Psi> = 0 with J = H_C + H_S: the global state is
an eigenstate of the joint generator, so nothing about it changes, while
conditioning on the clock still yields |psi(t)> = U^t |psi(0)>.

A TECHNICAL DISCOVERY, recorded because it changes the state we prepare.
The history state used in IBM-0..IBM-4 takes U = Ry(2*pi/d), for which

    U^d = Ry(2*pi) = -I        (NOT +I)

so that state is invariant under (S (x) U) only up to a sign on the single
wraparound term -- it is a PW history state in the conditional sense but NOT
exactly cyclically stationary. This run therefore uses the phase generator

    U = P(2*pi/d) = diag(1, e^{2*pi*i/d}),   U^d = +I exactly

with the system prepared in |+>, giving |psi(t)> = (|0> + e^{i t theta}|1>)/sqrt2
and conditional evolution <X_S|t> = cos(2*pi*t/d) -- the same cosine signature
IBM-0 measured in Z, now generated by a phase rather than a rotation, and now
EXACTLY cyclic. Same construction, generator chosen so the constraint closes.

MEASUREMENT. Stationarity is tested by a Loschmidt echo: prepare with V,
apply the operator, un-prepare with V-dagger, and measure the probability of
returning to |0...0>, which equals |<Psi| A (x) B |Psi>|^2. One circuit per
arm; no tomography.

ARMS (all four are the SAME echo circuit with a different middle operator):
  joint        S (x) U     -> 1 exactly if the constraint holds
  clock_only   S (x) I     -> cos^2(theta/2)   (clock advanced, system not)
  system_only  I (x) U     -> cos^2(theta/2)   (system evolved, clock not)
  wrong_way    S (x) U^-1  -> cos^2(theta)     (clock forward, system backward)

Only the correctly PAIRED operation preserves the state. That pairing is the
constraint.

THE LINK to internal evolution: a fifth arm measures <X_S|t> from the same
|Psi>, confirming it tracks cos(2*pi*t/d). The SAME gate U that compensates
the clock shift in the echo is the one generating that conditional sequence
-- the script asserts this structurally (identical construction call), so the
two halves are demonstrably the same U, not merely similar numbers.

Usage:
    python pw_ibm5_constraint.py --dry
    python pw_ibm5_constraint.py --backend ibm_marrakesh
"""

from __future__ import annotations

import argparse
import datetime
import json
from pathlib import Path

import numpy as np
from qiskit import ClassicalRegister, QuantumCircuit
from qiskit.quantum_info import Statevector

from pw_ibm1_submit import DryBackend, HardwareBackend, clear_checkpoint, find_chain

CLOCK_SIZES = (2, 3)     # d = 4, 8
SHOTS = 4000


# --------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------

def system_step(qc: QuantumCircuit, system: int, theta: float, inverse: bool = False) -> None:
    """U = P(theta) (or its inverse). THE one-tick system evolution. Used both
    inside the echo's joint operator and (via prepare_history) to generate the
    conditional sequence -- deliberately a single function so the two uses are
    provably the same operator."""
    qc.p(-theta if inverse else theta, system)


def clock_shift(qc: QuantumCircuit, clock: list[int], inverse: bool = False) -> None:
    """Cyclic increment S|t> = |t+1 mod d> (or decrement). Standard ripple
    construction: MCX cascade from the top down, then X on the LSB."""
    n = len(clock)
    if inverse:
        qc.x(clock[0])
        for k in range(1, n):
            qc.mcx(clock[:k], clock[k])
    else:
        for k in range(n - 1, 0, -1):
            qc.mcx(clock[:k], clock[k])
        qc.x(clock[0])


def prepare_history(n_clock: int) -> QuantumCircuit:
    """V: |0...0> -> |Psi> = (1/sqrt d) sum_t |t> (x) U^t|+>, U = P(2 pi / d).

    Clock into uniform superposition, system into |+>, then a controlled-phase
    ladder CP(2^k * theta) from clock qubit k, which imprints e^{i t theta}
    on the system's |1> component -- exactly U^t conditioned on |t>."""
    d = 2**n_clock
    theta = 2.0 * np.pi / d
    clock, system = list(range(n_clock)), n_clock
    qc = QuantumCircuit(n_clock + 1, name="V")
    qc.h(clock)
    qc.h(system)
    for k, cq in enumerate(clock):
        qc.cp((2**k) * theta, cq, system)
    return qc


def build_echo(n_clock: int, shift: bool, evolve: int) -> QuantumCircuit:
    """V-dagger . (S^shift (x) U^evolve) . V , then measure everything.
    P(|0...0>) = |<Psi| S^shift (x) U^evolve |Psi>|^2."""
    d = 2**n_clock
    theta = 2.0 * np.pi / d
    clock, system = list(range(n_clock)), n_clock
    v = prepare_history(n_clock)
    qc = QuantumCircuit(n_clock + 1)
    qc.compose(v, inplace=True)
    if shift:
        clock_shift(qc, clock)
    if evolve == 1:
        system_step(qc, system, theta)
    elif evolve == -1:
        system_step(qc, system, theta, inverse=True)
    qc.compose(v.inverse(), inplace=True)
    qc.add_register(ClassicalRegister(n_clock + 1, "c"))
    qc.measure(range(n_clock + 1), range(n_clock + 1))
    return qc


def build_conditional(n_clock: int) -> QuantumCircuit:
    """Same |Psi>, clock read in Z and system in X: <X_S|t> = cos(2 pi t/d)."""
    clock, system = list(range(n_clock)), n_clock
    qc = QuantumCircuit(n_clock + 1)
    qc.compose(prepare_history(n_clock), inplace=True)
    qc.h(system)                      # X-basis readout
    qc.add_register(ClassicalRegister(n_clock + 1, "c"))
    qc.measure(range(n_clock + 1), range(n_clock + 1))
    return qc


# --------------------------------------------------------------------------
# Readout
# --------------------------------------------------------------------------

def return_probability(counts: dict[str, int]) -> float:
    total = sum(counts.values())
    zeros = next((v for k, v in counts.items() if set(k.replace(" ", "")) == {"0"}), 0)
    return zeros / max(total, 1)


def conditional_x(counts: dict[str, int], n_clock: int) -> dict[int, float]:
    per_t = {t: [0, 0] for t in range(2**n_clock)}
    for bits, n in counts.items():
        b = bits.replace(" ", "")
        per_t[int(b[1:], 2)][int(b[0])] += n
    return {t: ((v[0] - v[1]) / (v[0] + v[1]) if sum(v) else float("nan"))
            for t, v in per_t.items()}


def exact_overlap(n_clock: int, shift: bool, evolve: int) -> float:
    """|<Psi| S (x) U |Psi>|^2 from statevector -- circuits, not hand algebra."""
    qc = build_echo(n_clock, shift, evolve).remove_final_measurements(inplace=False)
    return float(abs(Statevector.from_instruction(qc).data[0]) ** 2)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true")
    ap.add_argument("--backend", default=None)
    ap.add_argument("--fresh", action="store_true")
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args()

    ARMS = (("joint", True, 1), ("clock_only", True, 0),
            ("system_only", False, 1), ("wrong_way", True, -1))

    print("=== CONSTRAINT PREDICTIONS (statevector, from the real circuits) ===")
    preds = {}
    for n_clock in CLOCK_SIZES:
        d = 2**n_clock
        theta = 2.0 * np.pi / d
        p = {name: exact_overlap(n_clock, sh, ev) for name, sh, ev in ARMS}
        analytic = {"clock_only": float(np.cos(theta / 2) ** 2),
                    "system_only": float(np.cos(theta / 2) ** 2),
                    "wrong_way": float(np.cos(theta) ** 2)}
        preds[str(d)] = {"echo": p, "analytic_controls": analytic}
        print(f"  d={d}: joint={p['joint']:.4f}  clock_only={p['clock_only']:.4f}  "
              f"system_only={p['system_only']:.4f}  wrong_way={p['wrong_way']:.4f}")
        print(f"        analytic controls cos^2(th/2)={analytic['clock_only']:.4f}  "
              f"cos^2(th)={analytic['wrong_way']:.4f}   "
              f"[stationary: {abs(p['joint']-1.0) < 1e-9}]")
        assert abs(p["joint"] - 1.0) < 1e-9, "joint operator is NOT a symmetry; constraint broken"
        for k, v in analytic.items():
            assert abs(p[k] - v) < 1e-9, f"{k} disagrees with closed form"

    backend = DryBackend() if args.dry else HardwareBackend(args.backend)
    if args.fresh and not args.dry:
        clear_checkpoint(backend.name)
    out_dir = args.out_dir or Path(f"results_ibm5_{backend.name}")
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.utcnow().isoformat() + "Z"
    print(f"\nAQ-PAGE-WOOTTERS-IBM-5  backend={backend.name}  dry={args.dry}  {ts}", flush=True)

    chain = find_chain(backend.coupling_map, backend.num_qubits, max(CLOCK_SIZES) + 1)
    prereg = {"program": "AQ-PAGE-WOOTTERS-IBM-5", "backend": backend.name,
              "dry_run": bool(args.dry), "submission_time": ts, "optimization_level": 0,
              "shots": SHOTS, "predictions": preds,
              "generator": "U = P(2*pi/d) phase gate; U^d = +I exactly (Ry version is -I)",
              "gates": {
                  "gate1_stationary": "joint echo return-probability is the largest of the four arms",
                  "gate2_beats_controls": "joint exceeds every control by > 3x combined shot noise",
                  "gate3_controls_track_theory": ("clock_only/system_only/wrong_way within 0.1 of "
                                                  "closed form AFTER normalising by the joint arm, "
                                                  "whose exact value is 1.0 and which therefore "
                                                  "calibrates this circuit's echo attenuation in-run"),
                  "gate4_conditional_recovered": "R^2 > 0.90 for <X_S|t> vs cos(2 pi t/d)",
              }}
    (out_dir / "ibm5_prereg.json").write_text(json.dumps(prereg, indent=2), encoding="utf-8")
    print(f"  pre-registration filed: {out_dir / 'ibm5_prereg.json'}", flush=True)

    results = {"backend": backend.name, "predictions": preds, "arms": {}}
    gates = {}

    for n_clock in CLOCK_SIZES:
        d = 2**n_clock
        layout = chain[:n_clock + 1]
        print(f"\n=== d={d} ===", flush=True)

        circuits = [build_echo(n_clock, sh, ev) for _, sh, ev in ARMS] + [build_conditional(n_clock)]
        counts, _ = backend.run_batch(circuits, SHOTS, layout, stage=f"constraint_d{d}")

        echo = {name: return_probability(counts[i]) for i, (name, _, _) in enumerate(ARMS)}
        sigma = 1.0 / np.sqrt(SHOTS)
        cx = conditional_x(counts[-1], n_clock)
        x_meas = np.array([cx[t] for t in range(d)])
        x_pred = np.array([np.cos(2 * np.pi * t / d) for t in range(d)])
        a = float(np.dot(x_pred, x_meas) / np.dot(x_pred, x_pred))
        r2 = float(1 - np.sum((x_meas - a * x_pred) ** 2)
                   / max(np.sum((x_meas - x_meas.mean()) ** 2), 1e-12))

        # The joint arm's EXACT value is 1.0, so its measured value is a direct
        # in-run calibration of this circuit's echo attenuation -- deeper
        # circuits (the d=8 shift needs a Toffoli) attenuate every arm
        # together. Comparing raw controls against exact values ignores that
        # and fails on depth alone; normalising by the joint arm is the same
        # in-run-baseline correction the IBM-0 ledger identified as the right
        # design after its Gate 3 failed on both replications.
        attenuation = echo["joint"]
        normalised = {k: (v / attenuation if attenuation > 1e-9 else float("nan"))
                      for k, v in echo.items()}
        results["arms"][str(d)] = {"echo": echo, "echo_normalised": normalised,
                                   "echo_attenuation": attenuation,
                                   "conditional_x": cx,
                                   "conditional_amplitude": a, "conditional_r2": r2}
        for name in echo:
            print(f"  echo {name:12s} = {echo[name]:.4f}  norm={normalised[name]:.4f}   "
                  f"(exact {preds[str(d)]['echo'][name]:.4f})", flush=True)
        print(f"  echo attenuation (joint arm, exact 1.0) = {attenuation:.4f}", flush=True)
        print(f"  conditional <X|t>: amplitude {a:.4f}  R^2 {r2:.4f}", flush=True)

        worst_ctrl = max(v for k, v in echo.items() if k != "joint")
        gates[f"gate1_stationary_d{d}"] = bool(echo["joint"] == max(echo.values()))
        # Significance uses the ACTUAL per-arm binomial sigma, sqrt(p(1-p)/N),
        # not the worst-case 1/sqrt(N). The 2026-08-08 run used the worst-case
        # form (attained only at p=0.5) and therefore demanded a 0.0671 gap
        # where the true 1-sigma uncertainty was 0.0095; the d=8 joint-vs-
        # system_only gap of 0.0557 was recorded as a FAILURE at the
        # pre-registered bar despite being 5.9 sigma by the correct statistic.
        # Same class of error as IBM-1's hardcoded gate slack: a threshold
        # that did not track the actual noise. Fixed here for future runs; the
        # 2026-08-08 verdict stands as registered in that run's results doc.
        def sig(a: float, b: float) -> float:
            va = a * (1.0 - a) / SHOTS
            vb = b * (1.0 - b) / SHOTS
            return (a - b) / max(np.sqrt(va + vb), 1e-12)
        sigmas = {k: sig(echo["joint"], v) for k, v in echo.items() if k != "joint"}
        results["arms"][str(d)]["control_sigmas"] = sigmas
        gates[f"gate2_beats_controls_d{d}"] = bool(min(sigmas.values()) > 3.0)
        gates[f"gate3_controls_track_theory_d{d}"] = bool(all(
            abs(normalised[k] - preds[str(d)]["echo"][k]) < 0.10
            for k in ("clock_only", "system_only", "wrong_way")))
        gates[f"gate4_conditional_recovered_d{d}"] = bool(r2 > 0.90)

    results["gates"] = gates
    results["all_gates_pass"] = bool(all(gates.values()))
    results["job_ids"] = getattr(backend, "job_ids", [])
    results["layouts"] = {str(2**nc): chain[:nc + 1] for nc in CLOCK_SIZES}
    (out_dir / "ibm5_results.json").write_text(json.dumps(results, indent=2, default=str), encoding="utf-8")
    if not args.dry:
        clear_checkpoint(backend.name)
    print(f"\n[GATES] {json.dumps(gates, indent=2)}")
    print(f"[DONE] all_gates_pass={results['all_gates_pass']}  -> {out_dir / 'ibm5_results.json'}")


if __name__ == "__main__":
    main()
